updated scripts to acds/acl 17.1.1. Also added some ASE hacks because of runtime linking issue.

diff --git a/ase/scripts/program b/ase/scripts/program
--- a/ase/scripts/program
+++ b/ase/scripts/program
@@ -3,6 +3,19 @@
 echo $1
 echo $2
 
+
+filename=$(basename "$2")
+extension="${filename##*.}"
+
+fpga_bin_path=$2
+
+if [ "$extension" == "aocx" ]; then
+	fpga_bin_path="fpga.bin"
+	aocl binedit $2 get .acl.fpga.bin $fpga_bin_path
+fi
+
+echo $fpga_bin_path
+
 if [ "$OPENCL_ASE_SIM" == "1" ]; then
 	#simulation programming flow(start VCS)
 	if [[ "$1" != "acl0" ]] ; then
@@ -11,10 +24,9 @@ if [ "$OPENCL_ASE_SIM" == "1" ]; then
 	fi                                                                                     
 	
 	#uncompress and prepare modelsim files
-	cp -rf $2 simulation.tar.gz
 	mkdir -p temp_simulation
 	cd temp_simulation
-	tar zxvf $2 
+	tar zxvf ../$fpga_bin_path
 	export KDIR=$PWD
 	
 	rm -fr ./ase
@@ -36,28 +48,7 @@ if [ "$OPENCL_ASE_SIM" == "1" ]; then
 	bash run_sim.sh
 
 else
-	#HW programming, run aal configuration program
-	#TODO: need to create custom reprogram utility so that we don't use this sample program.  Also using this path is a hack
-	
-	#reconfigure pll
-	#TODO update reconfigure PLL flow
-	#aocl binedit $2 get .acl.pll $2.pll
-	
-	#reprogram 
-	aocl binedit $2 exists .acl.gbs.gz
-	RESULT=$?
-	
-	if [ $RESULT -eq 0 ]; then
-		aocl binedit $2 print .acl.gbs.gz | gzip -dc > $2.gbs
-	else
-		aocl binedit $2 get .acl.gbs $2.gbs
-	fi
-	
-	#TODO: Fix hack of calling sudo
-	sudo $OPAE_INSTALL_PATH/bin/fpgaconf -v $2.gbs
-	RESULT=$?
-	rm -rf $2.gbs 
-	
-	exit $RESULT
+	echo "ERROR: HW configuration is not supported with this script"
+	exit 1
 fi
 
